In [360]:
import pandas as pd
import numpy as np
import re
import warnings
warnings.filterwarnings('ignore')

In [361]:
bowl1= pd.read_csv("C:/python projects/scraping csv files/bowling_records1.csv")
bowl1.head()

,Player,span,matches,innings,balls,overs,maidens,runs,wickets,BBI,BBM,average,economy,strike rate,four wicket haul,fifer
0,PWH de Silva (SL),2021-2021,8,8,180,30.0,-,156,16,3/9,3/9,9.75,5.20,11.25,-,-
1,A Zampa (AUS),2021-2021,7,7,162,27.0,-,157,13,5/19,5/19,12.07,5.81,12.46,-,1
2,TA Boult (NZ),2021-2021,7,7,166,27.4,-,173,13,3/17,3/17,13.30,6.25,12.76,-,-
3,Shakib Al Hasan (BAN),2021-2021,6,6,132,22.0,-,123,11,4/9,4/9,11.18,5.59,12.00,1,-
4,JR Hazlewood (AUS),2021-2021,7,7,144,24.0,1,175,11,4/39,4/39,15.90,7.29,13.09,1,-

In [362]:
bowl1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 95 entries, 0 to 94
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Player            95 non-null     object
 1   span              95 non-null     object
 2   matches           95 non-null     int64
 3   innings           95 non-null     int64
 4   balls             95 non-null     int64
 5   overs             95 non-null     float64
 6   maidens           95 non-null     object
 7   runs              95 non-null     int64
 8   wickets           95 non-null     int64
 9   BBI               95 non-null     object
 10  BBM               95 non-null     object
 11  average           95 non-null     float64
 12  economy           95 non-null     float64
 13  strike rate       95 non-null     float64
 14  four wicket haul  95 non-null     object
 15  fifer             95 non-null     object
dtypes: float64(4), int64(5), object(7)
memory usage: 12.0+ KB

In [363]:
bowl2= pd.read_csv("C:/python projects/scraping csv files/bowling_records2.csv")
bowl2.head()

,Player,span,matches,innings,balls,overs,maidens,runs,wickets,BBI,BBM,average,economy,strike rate,four wicket haul,fifer
0,PWH de Silva (SL),2022-2022,8,8,186,31.0,1,199,15,3/8,3/8,13.26,6.41,12.40,-,-
1,SM Curran (ENG),2022-2022,6,6,136,22.4,-,148,13,5/10,5/10,11.38,6.52,10.46,-,1
2,BFW de Leede (NED),2022-2022,8,7,132,22.0,-,169,13,3/19,3/19,13.00,7.68,10.15,-,-
3,B Muzarabani (ZIM),2022-2022,8,7,156,26.0,-,199,12,3/23,3/23,16.57,7.65,13.00,-,-
4,A Nortje (SA),2022-2022,5,5,105,17.3,-,94,11,4/10,4/10,8.53,5.37,9.54,2,-

In [364]:
bowl= pd.concat([bowl1,bowl2], axis=0, ignore_index=True)
bowl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Player            195 non-null    object
 1   span              195 non-null    object
 2   matches           195 non-null    int64
 3   innings           195 non-null    int64
 4   balls             195 non-null    int64
 5   overs             195 non-null    float64
 6   maidens           195 non-null    object
 7   runs              195 non-null    int64
 8   wickets           195 non-null    int64
 9   BBI               195 non-null    object
 10  BBM               195 non-null    object
 11  average           195 non-null    float64
 12  economy           195 non-null    float64
 13  strike rate       195 non-null    float64
 14  four wicket haul  195 non-null    object
 15  fifer             195 non-null    object
dtypes: float64(4), int64(5), object(7)
memory usage: 24.5+ KB

In [365]:
bowl['maidens']= bowl['maidens'].replace(to_replace='-',value='0')
bowl['four wicket haul']= bowl['four wicket haul'].replace(to_replace='-',value='0')
bowl['fifer']= bowl['fifer'].replace(to_replace='-',value='0')

bowl.head()

,Player,span,matches,innings,balls,overs,maidens,runs,wickets,BBI,BBM,average,economy,strike rate,four wicket haul,fifer
0,PWH de Silva (SL),2021-2021,8,8,180,30.0,0,156,16,3/9,3/9,9.75,5.20,11.25,0,0
1,A Zampa (AUS),2021-2021,7,7,162,27.0,0,157,13,5/19,5/19,12.07,5.81,12.46,0,1
2,TA Boult (NZ),2021-2021,7,7,166,27.4,0,173,13,3/17,3/17,13.30,6.25,12.76,0,0
3,Shakib Al Hasan (BAN),2021-2021,6,6,132,22.0,0,123,11,4/9,4/9,11.18,5.59,12.00,1,0
4,JR Hazlewood (AUS),2021-2021,7,7,144,24.0,1,175,11,4/39,4/39,15.90,7.29,13.09,1,0

In [366]:
b = pd.merge(bowl1,bowl2, on='Player',how='outer' )
b

,Player,span_x,matches_x,innings_x,balls_x,overs_x,maidens_x,runs_x,wickets_x,BBI_x,...,maidens_y,runs_y,wickets_y,BBI_y,BBM_y,average_y,economy_y,strike rate_y,four wicket haul_y,fifer_y
0,PWH de Silva (SL),2021-2021,8.0,8.0,180.0,30.0,-,156.0,16.0,3/9,...,1,199.0,15.0,3/8,3/8,13.26,6.41,12.4,-,-
1,A Zampa (AUS),2021-2021,7.0,7.0,162.0,27.0,-,157.0,13.0,5/19,...,-,80.0,5.0,2/19,2/19,16.00,6.66,14.4,-,-
2,TA Boult (NZ),2021-2021,7.0,7.0,166.0,27.4,-,173.0,13.0,3/17,...,-,148.0,8.0,4/13,4/13,18.50,7.40,15.0,1,-
3,Shakib Al Hasan (BAN),2021-2021,6.0,6.0,132.0,22.0,-,123.0,11.0,4/9,...,-,167.0,6.0,2/33,2/33,27.83,8.78,19.0,-,-
4,JR Hazlewood (AUS),2021-2021,7.0,7.0,144.0,24.0,1,175.0,11.0,4/39,...,-,124.0,5.0,2/33,2/33,24.80,8.26,18.0,-,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136,Afif Hossain (BAN),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-,11.0,1.0,1/11,1/11,11.00,11.00,6.0,-,-
137,Muhammad Waseem (UAE),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-,16.0,1.0,1/16,1/16,16.00,8.00,12.0,-,-
138,AK Markram (SA),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-,21.0,1.0,1/16,1/16,21.00,7.00,18.0,-,-
139,Aryan Lakra (UAE),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-,24.0,1.0,1/24,1/24,24.00,8.00,18.0,-,-
140,Ebadot Hossain (BAN),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-,25.0,1.0,1/25,1/25,25.00,7.89,19.0,-,-

In [367]:
b['maidens_x']= b['maidens_x'].replace(to_replace='-',value='0')
b['maidens_y']= b['maidens_y'].replace(to_replace='-',value='0')
b['four wicket haul_x']= b['four wicket haul_x'].replace(to_replace='-',value='0')
b['four wicket haul_y']= b['four wicket haul_y'].replace(to_replace='-',value='0')
b['fifer_x']= b['fifer_x'].replace(to_replace='-',value='0')
b['fifer_y']= b['fifer_y'].replace(to_replace='-',value='0')

In [368]:
b= b.fillna(0)
b['fifer_x'] = b['fifer_x'].astype(int)
b['fifer_y'] = b['fifer_y'].astype(int)
b['four wicket haul_x'] = b['four wicket haul_x'].astype(int)
b['four wicket haul_y'] = b['four wicket haul_y'].astype(int)
b['overs_x']=b['overs_x'].astype(int)
b['overs_y']=b['overs_y'].astype(int)
b['maidens_x']= b['maidens_x'].astype(int)
b['maidens_y']=b['maidens_y'].astype(int)
# b['BBI_x']= b['BBI_x'].astype(int)
# b['BBI_y']=b['BBI_y'].astype(int)

In [369]:
if '2022-2022' in b['span_y'].values:
    
    b.loc[b['span_y'] == '2022-2022', 'span_x'] = b['span_x'].replace('2021-2021', '2021-2022')
b['matches'] = b['matches_x'] + b['matches_y']
b['innings'] = b['innings_x'] + b['innings_y']
b['balls']= b['balls_x']+b['balls_y']
b['overs']= b['overs_x']+b['overs_y']
b['maidens']= b['maidens_x']+b['maidens_y']
b['runs']= b['runs_x']+b['runs_y']
b['wickets']=b['wickets_x']+ b['wickets_y']
b['average'] = b['runs']/b['wickets']
b['economy']=b['runs']/b['overs']
b['strikerate']= b['balls']/ b['wickets']
b['four wicket haul']=b['four wicket haul_x']+b['four wicket haul_y']
b['fifer']=b['fifer_x']+b['fifer_y']

b.rename(columns = {'span_x':'span'}, inplace = True)
b['span'] = b['span'].mask(b['span'] == 0, b['span_y'])
b.head()

,Player,span,matches_x,innings_x,balls_x,overs_x,maidens_x,runs_x,wickets_x,BBI_x,...,balls,overs,maidens,runs,wickets,average,economy,strikerate,four wicket haul,fifer
0,PWH de Silva (SL),2021-2022,8.0,8.0,180.0,30,0,156.0,16.0,3/9,...,366.0,61,1,355.0,31.0,11.451613,5.819672,11.806452,0,0
1,A Zampa (AUS),2021-2022,7.0,7.0,162.0,27,0,157.0,13.0,5/19,...,234.0,39,0,237.0,18.0,13.166667,6.076923,13.000000,0,1
2,TA Boult (NZ),2021-2022,7.0,7.0,166.0,27,0,173.0,13.0,3/17,...,286.0,47,0,321.0,21.0,15.285714,6.829787,13.619048,1,0
3,Shakib Al Hasan (BAN),2021-2022,6.0,6.0,132.0,22,0,123.0,11.0,4/9,...,246.0,41,0,290.0,17.0,17.058824,7.073171,14.470588,1,0
4,JR Hazlewood (AUS),2021-2022,7.0,7.0,144.0,24,1,175.0,11.0,4/39,...,234.0,39,1,299.0,16.0,18.687500,7.666667,14.625000,1,0

In [370]:
b.rename(columns = {'BBM_x':'BBM_2021'}, inplace = True)
b.rename(columns = {'BBM_y':'BBM_2022'}, inplace = True)

In [371]:
b=b.drop(['BBI_x','BBI_y','matches_x','economy_y','innings_x','innings_y','balls_x','balls_y','maidens_x','runs_x','overs_y','strike rate_x','strike rate_y','wickets_y','wickets_x','runs_y','average_x','average_y' ,'fifer_x','fifer_y','four wicket haul_x','four wicket haul_y','economy_x','economy_y','overs_x','matches_y','maidens_y','span_y' ],axis=1)

In [372]:
b = b.sort_values(by='wickets', ascending=False)
cols=['Player',	'span',	'matches',	'innings',	'balls','overs','maidens','runs','wickets','BBM_2021','BBM_2022','average','economy','strikerate','four wicket haul','fifer']
b=b[cols]
b.to_csv('bowling_records.csv', index=False)
b

,Player,span,matches,innings,balls,overs,maidens,runs,wickets,BBM_2021,BBM_2022,average,economy,strikerate,four wicket haul,fifer
0,PWH de Silva (SL),2021-2022,16.0,16.0,366.0,61,1,355.0,31.0,3/9,3/8,11.451613,5.819672,11.806452,0,0
2,TA Boult (NZ),2021-2022,12.0,12.0,286.0,47,0,321.0,21.0,3/17,4/13,15.285714,6.829787,13.619048,1,0
6,A Nortje (SA),2021-2022,10.0,10.0,221.0,36,0,198.0,20.0,3/8,4/10,9.900000,5.500000,11.050000,2,0
8,Shadab Khan (PAK),2021-2022,13.0,13.0,294.0,49,0,303.0,20.0,4/26,3/22,15.150000,6.183673,14.700000,1,0
1,A Zampa (AUS),2021-2022,10.0,10.0,234.0,39,0,237.0,18.0,5/19,2/19,13.166667,6.076923,13.000000,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,Mohammad Hafeez (PAK),2021-2021,6.0,4.0,36.0,6,0,52.0,1.0,1/16,0,52.000000,8.666667,36.000000,0,0
91,Karim Janat (AFG),2021-2021,5.0,4.0,48.0,8,0,72.0,1.0,1/7,0,72.000000,9.000000,48.000000,0,0
93,AC Evans (SCOT),2021-2021,3.0,3.0,48.0,8,0,86.0,1.0,1/22,0,86.000000,10.750000,48.000000,0,0
94,Mohammad Nabi (AFG),2021-2021,5.0,5.0,72.0,12,0,97.0,1.0,1/36,0,97.000000,8.083333,72.000000,0,0
140,Ebadot Hossain (BAN),2022-2022,1.0,1.0,19.0,3,0,25.0,1.0,0,1/25,25.000000,8.333333,19.000000,0,0